# SPDX-License-Identifier: LGPL-2.1-only
#
# Action to setup the libcgroup directory
#
# Copyright (c) 2020-2022 Oracle and/or its affiliates.
# Author: Tom Hromatka <tom.hromatka@oracle.com>
#

name: Setup the libcgroup directory
description: "Install dependencies, git clone, bootstrap, configure, and make libcgroup"
runs:
  using: "composite"
  steps:
  - run: |
      while sudo fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; do sleep 3; done
      sudo apt-get update
    shell: bash
  - run: |
      while sudo fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; do sleep 3; done
      sudo apt-get install libpam-dev lcov python3-pip python3-dev cmake bison flex byacc g++ autoconf automake libtool libsystemd-dev -y
    shell: bash
  - run: sudo pip install cython
    shell: bash
  - run: ./bootstrap.sh
    shell: bash
  - run: CFLAGS="$CFLAGS -g -O0 -Werror" ./configure --sysconfdir=/etc --localstatedir=/var --enable-code-coverage --enable-opaque-hierarchy="name=systemd" --enable-python
    shell: bash
  - run: make
    shell: bash
  - run: lcov -i -d . -c -o lcov.base
    shell: bash
