# SPDX-License-Identifier: LGPL-2.1-only
#
# Action to collate the libcgroup code coverage data
#
# Copyright (c) 2021-2022 Oracle and/or its affiliates.
# Author: Tom Hromatka <tom.hromatka@oracle.com>
#

name: Collate code coverage results
description: "Collate code coverage results"
runs:
  using: "composite"
  steps:
  - run: lcov -d . -c -o lcov.tests
    shell: bash
  - run: |
      lcov -r lcov.tests "/usr/include/python3.8/objimpl.h" \
                         "/usr/include/python3.8/object.h" \
                         "$(pwd)/src/python/libcgroup.c" \
                         "$(pwd)/src/parse.c" \
                         "$(pwd)/src/lex.c" \
                         -o lcov.tests
    shell: bash
  - run: |
      lcov -r lcov.base "/usr/include/python3.8/objimpl.h" \
                        "/usr/include/python3.8/object.h" \
                        "$(pwd)/src/python/libcgroup.c" \
                         "$(pwd)/src/parse.c" \
                         "$(pwd)/src/lex.c" \
                        -o lcov.base
    shell: bash
  - run: lcov -a lcov.base -a lcov.tests -o lcov.total
    shell: bash
